server:
  port: 8080
spring:
  redis:
    database: 0
    url: redis://user:@127.0.0.1:6379
    host: 127.0.0.1
    password:
    port: 6379
    ssl: false
    timeout: 5000s
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reserve?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000ms

mybatis:
  type-aliases-package: com.ac.reserve.web.api.domain
  mapper-locations: classpath:mapper/*.xml

weChat:
  appid: wx1a5f71aebc51e337
  secret: 45e58341e8a505dad4a09b2f322e4395

token:
  expirationMilliSeconds: 7200000

examine:
  url:
    applyExamineUrl: http://www.daxinghuodong.cn:8081/service/bskService/backgroundCheckService.action
    checkExamineUrl: http://www.daxinghuodong.cn:8081/service/bskService/backgroundCheckResult.action
  account:
    user: 2020hz
    password: 2020hz*_123


